CREATE DATABASE IF NOT EXISTS exemplo_autenticacao;
USE exemplo_autenticacao;

CREATE TABLE IF NOT EXISTS usuario (
    id INT PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(100) UNIQUE NOT NULL,
    senha CHAR(80)
);

CREATE TABLE IF NOT EXISTS mensagem (
    id INT PRIMARY KEY AUTO_INCREMENT,
    texto VARCHAR(255) NOT NULL,
    idUsuario INT,
    data DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (idUsuario) REFERENCES usuario(id)
);